http:
  # Add the router
  routers:
    web:
      entryPoints:
        - web
#      middlewares:
#        - my-basic-auth
      service: confluence
      rule: Host(`cd-confluence.skyguard.com.cn`)

#    people:
#      service: people-cn
#      rule: Host(`local.people.cn`)

  # Add the middleware
#  middlewares:
#    my-basic-auth:
#      basicAuth:
#        users:
#          - test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/
#          - test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0
#        usersFile: etc/traefik/.htpasswd

  # Add the service
  services:
    confluence:
      loadBalancer:
        servers:
          - url: http://172.30.3.224:10805
#        passHostHeader: false
#    people-cn:
#      loadBalancer:
#        servers:
#          - url: http://www.people.com.cn/
#        passHostHeader: false