# 配置80入口点，接收所有的HTTP流量
entryPoints:
  web:
    address: ":80"

# 对于文件，默认就是开启了watch
providers:
  file:
    filename: "cmd\\traefik\\config\\dynamic.yml"

# 启用dashboard
api:
  insecure: true
  dashboard: true
  debug: true